apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: wanntech-dk-tls
spec:
  secretName: wanntech-dk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wanntech.dk
  dnsNames:
    - wanntech.dk
    - www.wanntech.dk